# 公共配置文件
server:
  port: 1111
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 每次取 1 条消息进行消费，消费成功后再去取下一条消息
        # 防止多个消费者被均匀分配消息，让消费能力强的消费者能够获取更多的消息
        prefetch: 1
  cloud:
    nacos:
      server-addr: localhost:8848
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 8

  application:
    name: service
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memo
    username: root
    password: 125800
  # session 失效时间（分钟）
  session:
    redis:
      save-mode: on_set_attribute
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
