server:
  port: 9999
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, Pn #流量染色
      routes:
        - id: api_route
          uri: http://127.0.0.1:1111
          predicates:
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace