server:
  port: 9999
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, Pn #流量染色
      routes:
        - id: api_route
          uri: lb://service
          predicates:
            - Path=/**
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

